### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by udion** [PIQuIL/QuCumber#45]
Can someone point to the dataset on which algorithms can be tested?

Edit:
This paper https://arxiv.org/pdf/1703.05334.pdf
talks about the synthetic dataset, the procedure is not very clear to me, can someone point to some thorough references?

Thanks

**Comment by GTorlai** [comment]
Hi udion,
for training data, please refer to the examples folder. There, you find tutorials for reconstructing a positive and a complex wavefunction. In the respective folders, we have added all the data required to carry out the reconstruction (as .txt files). For the positive wavefunction, the data is generated with exact diagonalization for the transverse field Ising model at criticality (10 spins). For the complex wavefunction, the data is generated exactly for a 2-qubits state with random coefficients.

These two datasets are a good starting point to test the algorithms, since the size of the visible layer is small, but still, the data underlies non-trivial quantum states. If you are interested in larger system sizes, more sophisticated techniques are required to generate the data, such as tensor networks or quantum Monte Carlo (which was used in that paper).

Hope this helps,
Giacomo
