### ISSUE TITLE
RFC: Use iterator instead of callbacks

### ISSUE THREAD

**Issue by Roger-luo** [PIQuIL/QuCumber#63]
Callbacks can only happen in given position defined in the package, which prevents users to define their only operations during the training, it would be more convenient to have an iterator rather than callback.

A very simple way to implement this is just to add `yield` in some position at the training function:

https://github.com/PIQuIL/QuCumber/blob/de54f2f653dc0240d82679110fa975b5a24a8a1c/qucumber/nn_states/wavefunction.py#L496

or just wrap some functions together, and help user define their own `fit` function easier.

E.g in `torch.optim` simply use `step`/`zerograd`/`backward` as its interface, users will be able to warp these functions together simply with what they want to do during the training in a `train` function.

The `climin` doc explains why callback (black-box) is not good: https://climin.readthedocs.io/en/latest/

**Comment by emerali** [comment]
On the one hand, I like this idea because the added flexibility makes it easier to mess around with custom models, on the other hand, I'm not sure if the added flexibility would be worth it if it ends up resulting in more boilerplate/steeper learning curve.

The reasons I resorted to callbacks in the first place was because most other high-level frameworks (keras, skorch, etc.) use similar concepts, so it'd be easier for people to jump over; also, having a predefined `fit` function it makes things users who just want to train an RBM without having to write much of their own code.
