### ISSUE TITLE
missing .build_tools folder in v1.0.2 pip package

### ISSUE THREAD

**Issue by vthuongt** [PIQuIL/QuCumber#80]
I am currently unable to install QuCumber via pip even though it worked a couple of weeks ago on a similar machine. The error message is as follows:

> $pip install qucumber
Collecting qucumber
  Downloading https://files.pythonhosted.org/packages/69/6e/3cd0f3be01c2e835bd3233dfc8b9c304dea8bbca74cf5e5a4131348e9a79/qucumber-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zp_c5xyg/qucumber/setup.py", line 39, in <module>
        with open(".build_tools/readthedocs/requirements.txt", "r") as reqs:
    FileNotFoundError: [Errno 2] No such file or directory: '.build_tools/readthedocs/requirements.txt'
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-zp_c5xyg/qucumber/

I can install the bleeding edge-version from github. So I assume it is a problem with the package downloaded via pip? I tried downloading it manually indeed the folder __.build_tools__ is missing

**Comment by emerali** [comment]
Thanks for finding this bug! The issue stems from the fact that the pip package only contains the code required to run QuCumber, so auxiliary files like those in `.build_tools` won't be included. I've always been installing things locally, so that file has always been available, which is why I never encountered this bug. 

I'll push a fix later today.

**Comment by emerali** [comment]
The fixed package is now available :)

Please let me know if anything else goes wrong.
