### ISSUE TITLE
How is the RBM's partition function being calculated ?

### ISSUE THREAD

**Issue by andriusdc** [PIQuIL/QuCumber#81]
I didn't get how the partition function is being treated on QuCumber. Is it being calculated exactly in those tutorials examples? If it is, how do I manage it if I am running the RBM on a big system where calculating this function is intractable ?

**Comment by emerali** [comment]
For the tutorials, we are indeed computing the partition function exactly (by the function `.compute_normalization`) in order to compute certain exact training statistics such as the wavefunctions fidelity and KL divergence. Note that both of these quantities require you to know the true wavefunction that you'd like to fit against, so they are only really useful for simple examples such as those shown in the tutorials.

For large systems you really just shouldn't be computing the partition function in the first place, and often-times the true wavefunction itself may not be known or may not be feasible to store in memory due to the exponential scaling in the number of lattice sites. In such cases training statistics like fidelity and KL are impossible to calculate, so you probably don't even need the partition function in the first place.

In the tutorial 1 you can prevent computation of the partition function by not passing the `MetricEvaluator` callback to the fit function. You will however no longer be able to run the rest of the tutorial following the training step as those cells require data produced by the `MetricEvaluator`.

**Comment by andriusdc** [comment]
Thank you for your answer !

So, if I am studying large systems, what should I do to get information about the state ? I mean, what useful resources I can get from the RBM, knowing that I cant calculate the partition function, and how do I get then ? Is there any bibliography reference about those cases where the partition function is impossible to calculate ?

**Comment by emerali** [comment]
For larger systems the main source of information on the state is achieved by drawing samples from the state and analyzing the drawn samples in some way; with images, for example, you just look at the outputs.

A more rigorous way that is more relevant for quantum systems would be to estimate observables using the drawn samples. QuCumber already has ways of doing this, which are explained in tutorials 3 ([link](https://qucumber.readthedocs.io/en/stable/_examples/Tutorial3_DataGeneration_CalculateObservables/tutorial_sampling_observables.html)) and 4 ([link](https://qucumber.readthedocs.io/en/stable/_examples/Tutorial4_MonitoringObservables/tutorial_monitor_observables.html)).

I don't know of any such references off the top of my head, but I believe almost all practical uses of RBMs have intractable partition functions.
